apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/app: openhouse
    app.kubernetes.io/service: {{ .Release.Name }}
    app.kubernetes.io/tag: {{ .Values.openhouseClusterTag }}
spec:
{{- if eq .Values.tablesService.service.type "LoadBalancer" }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: {{ .Values.tablesService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/service: {{ .Release.Name }}
    app.kubernetes.io/tag: {{ .Values.openhouseClusterTag }}
    app.kubernetes.io/instance: {{ .Release.Name }}
