version: "3.3"
services:
  namenode:
    image: bde2020/hadoop-namenode:1.2.0-hadoop2.8-java8
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop/hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:1.2.0-hadoop2.8-java8
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - 9864:9864
      - 9866:9866
    env_file:
      - hadoop/hadoop.env
