package harness

/** Mixes every standard capability trait into one catalog source. */
object Scenarios
    extends ScenarioAccessControl
    with ScenarioChangelog
    with ScenarioColumnTag
    with ScenarioCompactionPlanning
    with ScenarioConcurrency
    with ScenarioDataType
    with ScenarioDml
    with ScenarioDmlValidation
    with ScenarioEncryption
    with ScenarioFileFormat
    with ScenarioFileReplication
    with ScenarioIncrementalRead
    with ScenarioLocking
    with ScenarioMaintenance
    with ScenarioMetadataTable
    with ScenarioNamespace
    with ScenarioNestedType
    with ScenarioPartitionEvolution
    with ScenarioPartitionTransform
    with ScenarioProcedure
    with ScenarioRename
    with ScenarioScanPlanning
    with ScenarioSchemaEvolution
    with ScenarioSnapshotRestore
    with ScenarioSortOrder
    with ScenarioStreaming
    with ScenarioTableEvolutionCompatibility
    with ScenarioTableProperty
    with ScenarioTimeTravel
    with ScenarioWriteDistribution
    with ScenarioWriterCompatibility
