package harness

/** Mixes every standard capability trait into one catalog source. */
object Scenarios
    extends AccessControlScenarios
    with ChangelogScenarios
    with ColumnTagScenarios
    with CompactionPlanningScenarios
    with ConcurrencyScenarios
    with DataTypeScenarios
    with DmlScenarios
    with DmlValidationScenarios
    with EncryptionScenarios
    with FileFormatScenarios
    with FileReplicationScenarios
    with IncrementalReadScenarios
    with LockingScenarios
    with MaintenanceScenarios
    with MetadataTableScenarios
    with NamespaceScenarios
    with NestedTypeScenarios
    with PartitionEvolutionScenarios
    with PartitionTransformScenarios
    with ProcedureScenarios
    with RenameScenarios
    with ScanPlanningScenarios
    with SchemaEvolutionScenarios
    with SnapshotRestoreScenarios
    with SortOrderScenarios
    with StreamingScenarios
    with TableEvolutionCompatibilityScenarios
    with TablePropertyScenarios
    with TimeTravelScenarios
    with WriteDistributionScenarios
    with WriterCompatibilityScenarios
