cluster.metadata.database.url=${OPENHOUSE_DB_URL:jdbc:mysql://localhost:3306/oh_db}
cluster.metadata.database.username=${OPENHOUSE_DB_USER:oh_user}
cluster.metadata.database.password=${OPENHOUSE_DB_PASSWORD:oh_password}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
