spring.application.name=openhouse-optimizer-service
server.port=8080

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:db/optimizer-schema.sql

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${OPTIMIZER_DB_URL:jdbc:mysql://localhost:3306/oh_db}
spring.datasource.username=${OPTIMIZER_DB_USERNAME:oh_user}
spring.datasource.password=${OPTIMIZER_DB_PASSWORD:oh_password}
spring.datasource.hikari.maximum-pool-size=20

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.enabled=true
