name: Bug Report
description: Create a bug report to help us reproduce the bug and fix it.
labels: 'bug'
title: '[BUG]'

body:
- type: markdown
  attributes:
    value: |
      Thank you for submitting an issue.
      #### Please fill in this bug report template to ensure a timely and thorough response.

- type: dropdown
  id: contribution
  attributes:
    label: Willingness to contribute
    description: The OpenHouse Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this issue or bug to the OpenHouse code base?
    options:
      - Yes. I can contribute a fix for this bug independently.
      - Yes. I would be willing to contribute a fix for this bug with guidance from the OpenHouse community.
      - No. I cannot contribute a bug fix at this time.
  validations:
    required: true

- type: input
  validations:
    required: true
  attributes:
    label: OpenHouse version
    description: OpenHouse version

- type: textarea
  attributes:
    label: System information
    description: |
      Describe the system where you encountered the bug.
    value: |
      - **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
      - **JDK version**:
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe the problem
    description: |
      Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior if it is a bug report.
  validations:
    required: true

- type: textarea
  attributes:
    label: Stacktrace, metrics and logs
    description: |
      Please provide the logs and errors for reproducibility.
  validations:
    required: false

- type: textarea
  attributes:
    label: Code to reproduce bug
    description: |
      Provide a reproducible test case that is the bare minimum necessary to generate the problem.
    placeholder: |
      ```java
      // test case to reproduce bug
      ```
  validations:
    required: false

- type: checkboxes
  id: component
  attributes:
    label: What component does this bug affect?
    description: Please choose one or more components below.
    options:
      - label: "`Table Service`: This is the RESTful catalog service that stores table metadata. `:services:tables`"
        required: false
      - label: "`Jobs Service`: This is the job orchestrator that submits data services for table maintenance. `:services:jobs`"
        required: false
      - label: "`Data Services`: This is the jobs that performs table maintenance. `apps:spark`"
        required: false
      - label: "`Iceberg internal catalog`: This is the internal Iceberg catalog for OpenHouse Catalog Service. `:iceberg:openhouse`"
        required: false
      - label: "`Spark Client Integration`: This is the Apache Spark integration for OpenHouse catalog. `:integration:spark`"
        required: false
      - label: "`Python DataLoader`: This is the distributed data loading library for OpenHouse tables. `:integrations:python:dataloader`"
        required: false
      - label: "`Documentation`: This is the documentation for OpenHouse. `docs`"
        required: false
      - label: "`Local Docker`: This is the local Docker environment for OpenHouse. `infra/recipes/docker-compose`"
        required: false
      - label: "`Other`: Please specify the component."
        required: false
