namespace: "default"

openhouseClusterTag: "openhouse"

clusterPropertiesPath: "config/azure/sandbox/cluster.yaml"

tablesService:
  replicaCount: 1
  image:
    tag: "latest"
    pullPolicy: Always
  service:
    type: LoadBalancer # Needed so that the client cluster can connect to the service via an external IP
    port: 8080
  port: 8080
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 2G
  command: "java -Xmx1024M -Xms128M -XX:NativeMemoryTracking=summary -cp tables.jar -Dloader.main=com.linkedin.openhouse.tables.TablesSpringApplication org.springframework.boot.loader.PropertiesLauncher $APP_NAME.jar $@"
  appName: tables-service
