spring.application.name=openhouse-optimizer-scheduler
spring.main.web-application-type=none
spring.datasource.url=${OPTIMIZER_DB_URL:jdbc:h2:mem:schedulerdb;DB_CLOSE_DELAY=-1;MODE=MySQL}
spring.datasource.username=${OPTIMIZER_DB_USER:sa}
spring.datasource.password=${OPTIMIZER_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
jobs.base-uri=${JOBS_BASE_URI:http://localhost:8002}
scheduler.bin-size-max-files=${SCHEDULER_BIN_SIZE_MAX_FILES:1000000}
scheduler.operation-type=${SCHEDULER_OPERATION_TYPE:ORPHAN_FILES_DELETION}
scheduler.results-endpoint=${SCHEDULER_RESULTS_ENDPOINT:http://openhouse-optimizer:8080/v1/table-operations}
scheduler.cluster-id=${SCHEDULER_CLUSTER_ID:LocalHadoopCluster}
