POST {{base-url}}
Content-Type: application/json

{
  "jobName": "ORPHAN_FILE_DELETION_db_tb",
  "clusterId": "LocalHadoopCluster",
  "jobConf": {
    "jobType": "ORPHAN_FILES_DELETION",
    "args": ["--tableName", "db.tb"]
}
}
> {%
    client.global.set("jobId", response.body.jobId);
%}

###
GET {{base-url}}/{{jobId}}
Accept: application/json

###
PUT {{base-url}}/{{jobId}}/cancel
Accept: application/json
