POST {{base-url}}
Content-Type: application/json

{
  "jobName": "SNAPSHOT_EXPIRATION_db_tb",
  "clusterId": "LocalHadoopCluster",
  "jobConf": {
    "jobType": "SNAPSHOTS_EXPIRATION",
    "proxyUser": "DUMMY_ANONYMOUS_USER",
    "args": [
      "--tableName", "db.tb",
      "--granularity", "day",
      "--maxAge", 1
    ]
  }
}
> {%
    client.global.set("jobId", response.body.jobId);
%}

###
GET {{base-url}}/{{jobId}}
Accept: application/json

###
PUT {{base-url}}/{{jobId}}/cancel
Accept: application/json
